In [62]:
import torch
import numpy as np

In [2]:
t = torch.Tensor(6)

In [61]:
torch.distributions.Normal(t[0], 1).sample()

tensor(-0.1529)

In [133]:
    dtypes = [
        ('step', np.int32),
        ('predicted_V', np.float32),
        ('actual_V', np.float32),
        ('error', np.float32),
        ('action_id', np.int16),
        ('reward', np.float32),
        ('action', np.float32, (500))
    ]
#     for i in range((500)):
#         dtypes.append((f'action_{i}', np.int16))     

#     for i in range((5)):
#         dtypes.append((f'continous_{i}', np.float32))  

#     for i in range((5)):
#         dtypes.append((f'continous_chosen_{i}', np.float32)) 

    step_recordings = np.zeros(10, dtype=dtypes)

In [134]:
step_recordings.shape

(10,)

In [132]:
step_recordings

array([(0, 0., 0., 0., 0, 0., [0.7691848 , 0.70169383, 0.5041261 , 0.17481543, 0.1011913 , 0.54891473, 0.34959996, 0.74619675, 0.7611373 , 0.6579399 , 0.5110218 , 0.6513211 , 0.748365  , 0.535144  , 0.8366078 , 0.4105433 , 0.22959204, 0.9915953 , 0.7462391 , 0.7981261 , 0.50550115, 0.08763534, 0.7618154 , 0.6900133 , 0.65151477, 0.8586404 , 0.82661456, 0.30319878, 0.14521743, 0.8644655 , 0.7198978 , 0.48057878, 0.63364375, 0.79256254, 0.3089823 , 0.9420005 , 0.39558566, 0.99026936, 0.4317695 , 0.650311  , 0.17865357, 0.89662397, 0.88107955, 0.7539363 , 0.90646255, 0.58544326, 0.30036768, 0.73387396, 0.9468556 , 0.7226471 , 0.52925307, 0.93376213, 0.83733314, 0.04056505, 0.90173453, 0.95938605, 0.1150143 , 0.84775025, 0.31973535, 0.15812466, 0.3950961 , 0.0780801 , 0.5454801 , 0.6131987 , 0.8204049 , 0.7700707 , 0.5624642 , 0.62199944, 0.4535197 , 0.7836532 , 0.9955841 , 0.10727351, 0.8607487 , 0.99485046, 0.75294685, 0.35886127, 0.3986436 , 0.76391023, 0.01116576, 0.84947956, 0.6764739

In [118]:
step_recordings[0]['continous_0'] = 0

In [107]:
step_recordings[0] = (1, 2.3, 4.3, 2, 1, 10)

In [80]:
step_recordings['predicted_V'].shape

(10, 6)

In [81]:
step_recordings.dtype

dtype([('step', '<i4'), ('predicted_V', '<f4'), ('actual_V', '<f4'), ('error', '<f4'), ('action_id', '<i2'), ('reward', '<f4')])

In [83]:
x = np.zeros(3, dtype=('i4',[('r','u1'), ('g','u1'), ('b','u1'), ('a','u1')]))
x

array([0, 0, 0],
      dtype=(numpy.int32, [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]))

In [86]:
x = np.zeros(3, dtype=[('x','f4'),('y',np.float32),('value','f4',(2,2))])
x

array([(0., 0., [[0., 0.], [0., 0.]]), (0., 0., [[0., 0.], [0., 0.]]),
       (0., 0., [[0., 0.], [0., 0.]])],
      dtype=[('x', '<f4'), ('y', '<f4'), ('value', '<f4', (2, 2))])

In [95]:
x['x']

array([0., 0., 0.], dtype=float32)

In [115]:
%%timeit 
a = np.zeros(500)

1.13 µs ± 18.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [116]:
%%timeit 
a = np.zeros(500)
a = tuple(a)

43.9 µs ± 621 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [120]:
%%timeit
a = np.zeros(500)
for i in range(0, 500):
    step_recordings[0][f'action_{i}'] = a[i]

705 µs ± 19.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [125]:
np.append([
            10, 
            1,
            -1,
            -1,
            1,
            -1,
            ],
            [np.random.random(500),
            np.random.random(5),
            np.random.random(5)]
        ).flatten()

array([10, 1, -1, -1, 1, -1,
       array([0.85799979, 0.43267528, 0.94488534, 0.79298668, 0.05706155,
       0.44285336, 0.67123884, 0.4677867 , 0.35586196, 0.02424863,
       0.68332142, 0.45937337, 0.27372863, 0.35357067, 0.65600306,
       0.25640516, 0.06056544, 0.03852405, 0.05354945, 0.75891341,
       0.85025529, 0.31534123, 0.9118159 , 0.31873676, 0.88724884,
       0.10441003, 0.0511259 , 0.82013657, 0.62901833, 0.96542243,
       0.70763645, 0.50821475, 0.2353015 , 0.68441813, 0.7760901 ,
       0.44357925, 0.03687222, 0.38690233, 0.65016492, 0.01027713,
       0.40182818, 0.16495265, 0.60175099, 0.11015464, 0.64412741,
       0.18913662, 0.56188344, 0.62987051, 0.54397601, 0.25547831,
       0.04122961, 0.02667601, 0.35468357, 0.21217861, 0.02476804,
       0.27273233, 0.95687203, 0.80705745, 0.10480309, 0.76880112,
       0.03018714, 0.25117256, 0.29415735, 0.36080639, 0.00656911,
       0.69906802, 0.73932955, 0.90335801, 0.49379688, 0.24293743,
       0.49177458, 0.62100